# app/config/packages/artgris_file_manager.yaml
artgris_file_manager:
    conf:
        default:
            dir: '%kernel.project_dir%/public/uploads'

        images:
            dir: "%kernel.project_dir%/public/uploads"
            type: 'image'