vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        news_featured_images:
            uri_prefix: /uploads/images/news
            upload_destination: '%kernel.project_dir%/public/uploads/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        person_pictures:
            uri_prefix: /uploads/images/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        enrollment_documents:
            uri_prefix: /uploads/documents/preinscription
            upload_destination: '%kernel.project_dir%/public/uploads/documents/preinscription'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        partners_logos:
            uri_prefix: /uploads/images/partenaires
            upload_destination: '%kernel.project_dir%/public/uploads/images/partenaires'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
