controllers:
    resource: ../src/Controller/
    type: attribute

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:
        annotation
    prefix:
        /file-manager